### ISSUE TITLE
Spectating zombie NPCs

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#101]
This is a random silly idea that I think would be worth to mention here. 

How about to add an ability to spectate NPCs from their POV? This is something that might be nice to have as a small gimmick. Sure it might be very glitchy on practice if it would be in game, but it would simply give a nice piece of immersion to some players. Let's call this command something like "zm_spec_zombie_pov" or something like that.

As a default key for it you can set "Z" (which can be re-bound in options ofc), so as a spectator if you're aiming at some zombie and tap "Z" you will be switched to its POV. If you click "Mouse1", "Mouse2" or "Spacebar" in "Zombie POV" mode you will cycle through players (or quit Zombie POV in case with spacebar) like in normal spectating mode. For debugging, when in "Zombie POV" mode already, you shouldn't be able to use the "zm_spec_zombie_pov" command until you switch from it back to normal mode.

**Comment by DevilMudger** [comment]
This was already a feature in 1.2.1. It just hasn't been re-implemented yet.

**Comment by DoofusCockslap** [comment]
Wasn't it broken in 1.2.1? Can't remember.

**Comment by DevilMudger** [comment]
Na it worked. Not brilliantly but it worked.
