### ISSUE TITLE
[SUGGESTION] Implement source shader editor

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [zm-reborn/zmr-game#105]
source shader editor is a powerful In Game shader editor you can test in game shaders that you made that tool comes whit a set of shaders also you can merged shader editor shader whit the materialsystem [https://github.com/Biohazard90/source-shader-editor](url)

**Comment by TheRenegadist** [comment]
Would be very useful for getting that blood squirt effect I suggested above.
