### ISSUE TITLE
info_manipulate ent_fire interaction

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#106]
There is a lack of proper interaction via ent_fire for info_manipulate. There is no way you can trigger the info_manipulate manually unless you're playing as ZM. There should be an Output (like "Trigger", "Use", "Activate", "Press" etc) that will allow mappers to test the trap orbs without being forced to be on ZM team or use bots as human players.

**Comment by TotallyMehis** [comment]
I've added Press-input but if you really want to do it properly, use logic_relay instead.

e3cf08be9ca98825be08244ca8ed1b89975d8404
