### ISSUE TITLE
ZM taunts

### ISSUE THREAD

**Issue by TotallyMehis** [zm-reborn/zmr-game#111]
Allow ZM to play certain sounds, similar to The Hidden, to improve the atmosphere of the game.

**Comment by xXxToxicBlueDustxXx** [comment]
well, in the folder there's a file named "menu.cpp and .h" and "voice_menu.cpp" you can create a L4D's Voice Menu whit these files plus in the "multiplay_gamerules.cpp" there's functions related to voice Aka: Taunts
