### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by TotallyMehis** [zm-reborn/zmr-game#112]
~~- Dynamic link (info_link_dynamic) crash.
    * CAI_Pathfinder::IsLinkUsable, invalid string
    * Maps: zm_the_redqueen_biohazard_b1, zm_guineapig_beta5
    * All maps that have any links turned off will potentially crash.~~ (Workaround for now)
- ~~Player model precache crash~~ Precache crash (PrecacheModelComponents) ([linked list overflow?](https://www.mail-archive.com/search?l=hlds_linux@list.valvesoftware.com&q=subject:%22Re%5C%3A+%5C%5Bhlds_linux%5C%5D+Team+Fortress+2+Update+Released%22&o=newest&f=1))
    * Map: zm_underground_v13 (player model crash)
    * Map: zm_jisho_b2 (PrecacheModelComponents)
    * Most likely not exclusive to a map.
- CBaseEntity::CollisionRulesChanged() crash.
    * Maps: zm_4dtetris_new, zm_asdf_b5
- vphysics.dll crash on map start.
    * CBreakableProp::HandleFirstCollisionInteractions is where it enters to vphysics. The trace goes pretty deep.
    * Map: zm_coastal_carnage_b5
- vphysics.dll crash on map start. This is exclusively caused by vphysics and I don't think we can do anything about it.
    * Maps: zm_owl_v2
- vphysics.dll crash on zm_grind_b1. Haven't been able to see what's causing it. Getting near the meat freezer fan causes it. [Probably related to this](http://hlcoders.valvesoftware.narkive.com/fjhPTyRS/base-2013-sdk-stock-prerelease-2013-sdk-vphysics-bug-assured-vphysics-dll-hang-crash-when-physics)
- keyframe_rope material precache crash with custom material "cat/white"
    * Map: zm_jisho_b2

**Comment by xXxToxicBlueDustxXx** [comment]
because you don't have access to engine's Physics source, the only way that i thinks use the HMODULE module functions and fix it , but you need to know Hex-Edit because you need to point where's the function

**Comment by TotallyMehis** [comment]
I'm reopening this to let people to report maps that crash.

**Comment by TotallyMehis** [comment]
Another vphysics crash. Map unknown.

CServerGameDLL:LevelShutdown
CGlobalEntityList::Clear
CGlobalEntityList::CleanupDeleteList
PhysOnCleanupDeleteList <-- Crashes
