### ISSUE TITLE
Alien Swarm Main Menu

### ISSUE THREAD

**Issue by TheRenegadist** [zm-reborn/zmr-game#120]
Port the Alien Swarm menu UI over.

**Comment by TotallyMehis** [comment]
But why? I see no need to override any of the engine menus yet (options, create server). It's already possible to override the loading background and the menu ui.

**Comment by TheRenegadist** [comment]
I suggested this as the current menu we have is barebones and lackluster, a menu that looked ok back in 2007 but looks unfinished and poorly designed now. It would be nice to see the menu brought to the latest standards of Source such as it is in Alien Swarm/Left 4 Dead 2 and pared with some new live backgrounds would look very nice.

The menu is the first thing people see when opening the game and as it stands it isn't very impressive. Not only that but the AS menu brings several improvements and we could also build off of it and improve it.

**Comment by xXxToxicBlueDustxXx** [comment]
also you can merge the ZM Option whit the Option Panel The Momentum Team Import The GameUI Files From Alien Swarm, you can do it but will be a bit tedious, also you can use Bik Moies but you must bring back the Bik support ( you can apply the the Bik Fix From Source 2007 )
