### ISSUE TITLE
Remove Pressing "E" Twice to Pick Things Up

### ISSUE THREAD

**Issue by TheRenegadist** [zm-reborn/zmr-game#121]
Old: _Seems kind of pointless to have the carry weapon when pressing "E" on anything picks it up just fine. I've also noticed that there's a lack of input when pressing "E" on anything as I'm sure it's the mod switching to the Carry weapon before things can be picked up prompting the player to press "E" twice on items to pick them up.

This may require community feedback as some people might like the use of the Carry weapon._

New: It can become annoying and make things more difficult by having to press "E" twice to pick things up which is the mod forcing the carry weapon to be selected. This needs to be fixed so things can be more streamlined and take away the stress of having to rely on two presses instead of one.

**Comment by xXxToxicBlueDustxXx** [comment]
well in hl2mp_player.cpp there's a function that come whit hl2's the pickup object its just easy copy/paste the pickupobject code from hl2_player.cpp but we need fixes for example wen you thrown a prop the gun fire occur but in fact to remove the carry weapon (in fact is the physcannon) its hard and tedious to do that because its refence in the game code

**Comment by TheRenegadist** [comment]
Well, Mehis is very good at what he does. I'm sure he could work a fix in (A slight delay perhaps) for the pick up/drop off/throw of a prop or item. I'm also sure that Mehis could work out a way to remove it from the game without breaking everything and removing that double tap "E" to pickup objects.

**Comment by Fichtendummkopf** [comment]
The carry weapon should NOT be removed as is can also be used to push/pull physics objects for barricading etc.

**Comment by TheRenegadist** [comment]
I take back what I said, the main issue I have here isn't the weapon itself or its use, it's the act of having to press "E" twice to pick things up.
