### ISSUE TITLE
[Idea/Suggestion] Remplace The Old Path Findind system (AI Nodes) to NavMesh

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [zm-reborn/zmr-game#128]
As the title says, it would be good if the Nav Mesh (.nav files) were used instead of the AI Nodes (.ain), why? Because there are certain bugs with this system a well-known is that it can rarely happen that a node is out of the world or other bugs with these, what I want to get is that in the future ZM: R use the Nav Mesh (something like that how it was implemented in lambda wars) look at this if you are interested: https://github.com/Sandern/recastnavigation

and to replace the bots (which is currently poor navigation) you could use this implementation: https://github.com/WootsMX/sourcebots

**Comment by TotallyMehis** [comment]
Zombies now use the NAV mesh on the [npcr-branch](https://github.com/zm-reborn/zmr-game/tree/npcr).

**Comment by xXxToxicBlueDustxXx** [comment]
i see that implementation and is excellent, but i have a question. why don't you create a derivation of navmesh i mean css and tf2 have its own derivation for css its: CSNavMesh and for tf2 its CTFNavMesh you can look at nav_mesh_factory.cpp, its better because you don't need to deal whit base code instance, you derive your own navmesh class for example CZMRNavMesh

**Comment by xXxToxicBlueDustxXx** [comment]
also for the survivor bots its good to look at the Insource's Repository it has a bots that have components these components can extend the bot's AI without touching the bot's class but saddly the developter din't update it to use NextBot if you wanna look at the original repo: https://github.com/WootsMX/insource

and of course the stripe down code for source 2013: https://github.com/WootsMX/sourcebots
