### ISSUE TITLE
'physgun_interactions preferred_carryangles'  set in models not working with prop_physics

### ISSUE THREAD

**Issue by Fichtendummkopf** [zm-reborn/zmr-game#13]
This has never worked since the original ZM:
When you use a prop_physics that has preferred carryangles set in its model, they don't work.
In ZMR, they seem to be used when **dropping** the prop as it rotates to the set angles then, but it should use the angles when **pickung up** the prop (Would be useful for props like chainsaws, blowtorches etc. being oriented correctly when carried).
Just as in the original ZM, the preferred carryangles do work correctly when picking up a func_physbox with the 'Preferred Player Carry Angles' keyvalue set, and the 'Use Preferred Carry Angles' flag set, so maybe looking into how that entity is interacted with could help.

An example of the carryangles set in a model
$keyvalues
{
physgun_interactions
	{
	 	preferred_carryangles 	"-90 0 0"
        }
}

**Comment by TotallyMehis** [comment]
Only took about 2 years

**Comment by Fichtendummkopf** [comment]
Sorry to say, this still doesn't seem to work correctly.
On pickup, the prop orients itself to the carryangles "relative to the world", and only on dropping it, it orients itself to the carryangles relative to the player.
Position of prop on ground:
![zm_hard_impact_props0048](https://user-images.githubusercontent.com/31129400/76249465-aa6fb580-6243-11ea-971b-6ef1fde77663.jpg)
Orientation when picking up:
![zm_hard_impact_props0049](https://user-images.githubusercontent.com/31129400/76249471-ae033c80-6243-11ea-95e6-de5fe5ab74af.jpg)
Orientation when dropping:
![zm_hard_impact_props0050](https://user-images.githubusercontent.com/31129400/76249478-b0fe2d00-6243-11ea-8035-93d26a0f8f77.jpg)
Same series of images with a different initial orientation of the prop, it doesn't seem to be affected with the prop's spawn orientation:
![zm_hard_impact_props0045](https://user-images.githubusercontent.com/31129400/76249523-cd01ce80-6243-11ea-9ae1-8dfd772d9122.jpg)
![zm_hard_impact_props0046](https://user-images.githubusercontent.com/31129400/76249575-eacf3380-6243-11ea-9911-50a310656559.jpg)
![zm_hard_impact_props0047](https://user-images.githubusercontent.com/31129400/76249583-ef93e780-6243-11ea-83df-0d32ad04c130.jpg)

**Comment by TotallyMehis** [comment]
https://gfycat.com/blandleaneft
