### ISSUE TITLE
Game cannot find assets as they contain capital letters in their name which should be lowercase [linux]

### ISSUE THREAD

**Issue by ProfanedBane** [zm-reborn/zmr-game#132]
Got some spicy errors and unfound textures when using the game with Linux, copy pasting the entire contents of /materials/VGUI into /materials/vgui fixed it perfectly.

**Comment by TotallyMehis** [comment]
Yea, I had a hunch there'd be similar problems. Linux isn't fully supported, it's mainly there for dedicated servers. I'd recommend using wine for now.

**Comment by ProfanedBane** [comment]
Basically completely fixed the issue by running a script to rename everything to be lowercased, I believe Windows treats lowercase/uppercase names as one and the same, something Linux doesn't.
