### ISSUE TITLE
Banshees don't attack survivors.

### ISSUE THREAD

**Issue by Unash332** [zm-reborn/zmr-game#14]
Banshees just run up to survivors and don't attack and neither they try to leap at a survivor, the sounds play normally but the attack animation never plays and the survivors never receive damage.

Seems like this issue in particular only happens in some maps like holyhell, debunked and bluevelvet.

**Comment by TotallyMehis** [comment]
This bug was so old that I forgot to put it in the patch notes: a5fa9e3b95fe35a8f53cadec76cc0f836dfb945d

**Comment by TotallyMehis** [comment]
20ed59f44e29e5bad2b9a8ac75605b9b85afb9db fixes this.
