### ISSUE TITLE
Invisible hulk

### ISSUE THREAD

**Issue by TotallyMehis** [zm-reborn/zmr-game#147]
Multiple people encountered this yesterday at the same time. I haven't been able to reproduce it. Only fixed by restarting the game.

~~Maps, in order:~~
- ~~zm_blackmesa1_v2_final~~
- ~~zm_urban_escape_b3_fix~~
    - ~~Might've started here, but the map doesn't have any hulk spawns~~
- ~~zm_forestforthewicked_b9_zmr~~
    - ~~This is where it was encountered~~

**Comment by Fichtendummkopf** [comment]
Didn't we play zm_radiation before forestforthewicked? 
Because I thought the issue might have something to do with that one hulk from a trap that is made invisible by setting the template NPC's render mode to 'Don't Render' on radiation.

**Comment by TotallyMehis** [comment]
Yea, it was because of zm_radiation, but not because of the render mode. Same reason why blackmesa custom player textures are carried over to other maps; replacing game content. In this case the hulk model with HL2 fast zombie for the hulkshee.

Lesson: don't replace game content through maps.
