### ISSUE TITLE
How You Implement the C_Arms System?

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [zm-reborn/zmr-game#148]
I Am a little curios how you implement that system like gmod does? because i try it to implement in my mod but its not working

**Comment by TotallyMehis** [comment]
https://github.com/zm-reborn/zmr-game/blob/master/mp/src/game/client/c_baseanimating.h#L366
https://github.com/zm-reborn/zmr-game/blob/master/mp/src/game/shared/zmr/zmr_viewmodel.cpp
https://github.com/zm-reborn/zmr-game/blob/master/mp/src/game/server/zmr/zmr_player.cpp#L1248
