### ISSUE TITLE
[Minor / Suggestion] Custom Main Menu UI

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#156]
Old HL2DM menu has been there for decades and really looks ugly alongside with the other updates and improvements.

How about to update the main/pause menu to be something like menus in "Portal 2" , "NMRiH" or "Estranged: Act I"?

Also, gonna mention a flash-based menu prototype from ZM2 (not to be confused with menu UI from public releases). 

Not a high priority, but it would be a nice addition for the final release when all major implementations are done.

**Comment by TotallyMehis** [comment]
We have one now.
