### ISSUE TITLE
Improve Molotov (Few Suggestions)

### ISSUE THREAD

**Issue by xDadiKx** [zm-reborn/zmr-game#16]
Right now, the Molotov is bit, eh.
![20170822085046_1](https://user-images.githubusercontent.com/13087761/29552386-5ee1862a-8717-11e7-9016-600caaaeb8db.jpg)
The fire that is produced from the molotov is small, I remember from Original Zombie Master, they were a bit bigger.
Add a breaking glass sound once the molotov hits ground. I think there was a sound in the original.
![20170822085059_1](https://user-images.githubusercontent.com/13087761/29552430-97fe8c6e-8717-11e7-91d2-88d40049c3d8.jpg)
The lighter that produces the fire to light up the molotov, the fire sprite has a black background to it and it is not animated.

**NEW! Edit** 
Make molotovs bounce off walls or set fire to walls. Right now, if you throw a molotov at a wall, the molotov disappears and then fire appears on the floor instead.
**Edit again**
Or show that the molotov breaks on the walls and fire spits out from the point of molotov breaking to the floor.

**Comment by TotallyMehis** [comment]
Yeah, the current molotov sucks.

The fire sprite being black is thanks to engine upgrade. A quick qc edit and recompile should do it. It is animated, though.

I'll be looking into making the fire into a particle system.
