### ISSUE TITLE
[Gameplay Improvement] Reload Interrupting via Single Mouse-click

### ISSUE THREAD

**Issue by TheRenegadist** [zm-reborn/zmr-game#167]
This is a minor change but I feel it would help out a lot, we should change the reload interrupting to be one mouse-click instead of holding the mouse down. More times than none I'll be holding the mouse button down to interrupt the reload and the gun will fire without the intent of doing so. Changing the system to a single-mouse click should stop the reload and cut down on unnecessary shooting vs. holding down the mouse button.

**Comment by DoofusCockslap** [comment]
Maybe it would be better if we let people to pick from 3 options, a classic "hold +attack key to stop reloading", your suggestion as "tap +attack key to stop reloading" and last one as "hold +reload key to stop reloading".

**Comment by TotallyMehis** [comment]
I updated this recently.
Before it was that you had to hold down attack until the reload ended and it would cancel. Now you just need to press it once and it will cancel after the current reload ends.
