### ISSUE TITLE
Client crash when connecting to zm_lostintentions_b4

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#196]
Servers can load this map just fine, but any client connecting to the server has their game crash with no error imminently upon connecting. Map works fine in 1.2.1.

Not sure if this is a problem that can be fixed mod side, requires changing the map, or could be fixed by a custom config, but I don't have the symbols to look at the crash myself and wouldn't know what I was looking at if I did.

Crash dump: [https://www.dropbox.com/s/2gqqj2gjzah9dvw/hl2_4630212_crash_2018_10_17T12_49_32C0%20-%20zm_lostintentions_b4%20client%20crash.mdmp?dl=0](url)

**Comment by TotallyMehis** [comment]
Trace ends in vphysics. There's nothing I can do.

I looked up the map and there are two ragdolls hanging using phys_constraint. Those are giant red flags to me. If you really want to make a fix, I'd suggest removing them altogether.
