### ISSUE TITLE
[ Minor / Suggestion ] Playermodel client-sided chat notification

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#211]
Bring back chat notification that tells you what playermodel you're using currently when you change the model on the run. It was very useful in 1.2.1.

**Comment by TotallyMehis** [comment]
This is not the case? It should still print the new player model and the next time you can change it.

**Comment by DoofusCockslap** [comment]
I double checked it and it actually works. It does print the message, but only if you change your playermodel from options menu. If you attempt to change your playermodel via console or .cfg file it won't print anything except for "Wait X seconds before changing your model".
