### ISSUE TITLE
func_giveresources currently not in a working state

### ISSUE THREAD

**Issue by otterfiend** [zm-reborn/zmr-game#22]
As far as I can tell, zm_deathrun , zm_tetris_new , and other maps that add resources via func_giveresources are currently not working correctly. I'm not sure if the entity isn't implemented yet, or if you just weren't aware of a breaking change. 

I have only checked zm_deathrun's logic to verify this so far, but the creator of tetris_new (and deathrun) has explained to me that he used func_giveresources in those two maps.

For the sake of keeping mapping options open, I would recommend that entity be fixed.

**Comment by TotallyMehis** [comment]
Fixed: 65c51a31f1732c304df34a48085e6037def4374b
