### ISSUE TITLE
[ Bug / AI ] NPCs can see players through solid/opaque entities

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#221]
I recently noticed a weird behaviour of all zombie NPCs. Somehow the AI can see players through the solid entities, such as all sorts of props (to be confirmed) and certain brush-based entities (func_door, func_tracktrain, func_breakable, func_wall etc). This breaks a several scripted events on the maps.

Here are examples of the scripts affected by this weird behaviour:

1. On zm_kink, whenever you spawn a "Ninja Banshee" on a rooftop of one building, this banshee instantly disappears and drops a bomb for no reason, resulting in wasted resources for ZM.

Normally in 1.2.1 this banshee would disappear and spawn a bomb only if it's alerted by a player
(in other words, if any player gets in this banshee's line of sight).

2. On zm_frozenisland, there is a trap located in a warehouse, hidden inside one of the cargo containers. This trap spawns an immolator from a wooden crate, which stands inside of said container. If ZM will spawn this immolator when player is standing outside of a container (let's say he stands on top of a container), this immolator would still get alerted by a player somehow.

3. On zm_gasdump, when ZM uses hidden spawn on upper floor and players taking elevator up. In 1.2.1 zombies stay silent before elevator doors open. In current beta zombies can already spot survivors behind the elevator doors and will pile up at the doors.

**Comment by TotallyMehis** [comment]
2e4f4797 pretty much fixes these problems.
I don't think the zm_kink one is related to it, though.

**Comment by DoofusCockslap** [comment]
Well, that scripted banshee does that, only if it has any players in its sight. So, I guess that one should be investigated further. Unless other entities are involved in that script (like "enemy finder" point entity or something).
