### ISSUE TITLE
[ Suggestion / UI ] Spawn menu hotkeys option

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#222]
ZM 1.2.1 had similiar feature, but it wasn't executed very well (it used letter keys, which could mess with your controls, if you're playing with WASD movement scheme).

The idea is simple - You can spawn zombies by pressing 1-5 keys, while spawn menu is open

Note: When you don't have any spawn menus open, these keys don't do anything, obviously. Just mentioning it to avoid any possible glitches.

The hotkeys should be assigned in order how zombies are listed in spawn menus.

From top to bottom:
1 key - Spawns one shambler
2 key - Spawns one banshee
3 key - Spawns one drifter
4 key - Spawns one hulk
5 key - Spawns one immolator

Unfortunately this scheme doesn't work for "spawn x5 zombies in one click" option.

Besides just spawn keys, we could also have "Set Rally Point" hotkey.

**Comment by TotallyMehis** [comment]
What a coincidence, I was about to implement this.
