### ISSUE TITLE
[ Suggestion / Minor ] Unit selection

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#231]
Currently ZM can select single unit by simply clicking on unit's model, sounds good, huh? But when you want to select one individual unit, that is in the middle of a crowd, this is where the problem comes in. Other units are just getting in the way and you can't select that particular unit you want. How about to make an option that would disable selecting units by the model. I clearly remember that in 1.2.1 you could select units by clicking on their "circle-health-indicator" that is below them. It was much easier than it is now.

**Comment by TotallyMehis** [comment]
I don't think I'll be implementing this.
