### ISSUE TITLE
[ Suggestion / Gameplay / SDK ] Spawn entity improvements

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#233]
This one was originally suggested by other user on Discord:
Make the unit cost dynamically increase if ZM spams the same unit type too often in X seconds period of time. To prevent spam on chokepoints.

Some of my ideas:
Option in the spawner's hammer entity to set custom unit cost and a new global entity that controls unit cost for each unit type for the whole server affecting untouched spawn entities, excluding the ones that have their unit cost keyvalues modified by mapper already.

Also how about to add some I/O's for existing spawn entity that allows to set unit cost with certain value and disable/units?

Example:

OnTrigger genericspawnname SetBansheeCost 75 [2.15 sec]"
OnTrigger genericspawnname SetShamblerCost 5 [2.15 sec]"
OnTrigger genericspawnname DisableHulkSpawn [0.15 sec]"
OnTrigger genericspawnname EnableHulkSpawn [15.00 sec]"

**Comment by DoofusCockslap** [comment]
Extra suggestion:

Queue pausing when Spawn Orb is "Hidden" (via I/O's Outputs Hide/Unhide). Most notable example can be seen on a map "zm_desertskystation".

Simple situation: You have a queue with 10 shamblies; the map tells this spawn to "Hide"; if you don't close the spawn menu when it's hidden already you will notice that your queue keeps on going nowhere (need to confirm if that still takes your resources as I don't remember).

**Comment by TotallyMehis** [comment]
Having the spawn menu open while the spawn is "hidden" is a bug.
