### ISSUE TITLE
[ Bug / Sound ] func_door loud spam of movement sound

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#234]
Certain Func_ entities (mostly func_door and func_movelinear) on some maps tend to pile up their movement sounds resulting in loud-ass sound spam. Never happened on 1.2.1.

P.S.:
There is a chance that it's Valve's broken shit on Source 2013 and probably unfixable.

**Comment by TotallyMehis** [comment]
Insignificant.
