### ISSUE TITLE
Zombies don't swat func_physbox entities

### ISSUE THREAD

**Issue by TotallyMehis** [zm-reborn/zmr-game#236]
This was reported to me. Haven't tested yet.

**Comment by DoofusCockslap** [comment]
Map where you should test it: zm_exodus_finale; starting area in the human-spawn house basement; there is makeshift barricade with wooden gate that consists of 3 func_physbox entities, 2 of which are sitting on "phys_constraint" or "phys_ballsocket" entities (forgot which entity exactly that is); 3rd func_physbox is a small board blocking the said gate.

**Comment by TotallyMehis** [comment]
The reason why the finale hinged doors can't be swatted is because their mass goes past the swat limit.
