### ISSUE TITLE
[ Suggestion / SDK / Mapping] Brush based zombie spawn entity

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#247]
Suggested by Dunking Crumpers on Discord:

A brush entity that would work the same way as in L4D, Contagion and NMRiH. In addition to legacy "spawn nodes" system we have, how about to add a new system that allows mappers to link the spawn orbs to the brush volume, instead of using point entities we have now.

This also might shorten the time required to set up zombie spawns in hammer.

Instead of linking every spawn node like path_tracks in HL2, just add a volume that will spawn zombies within itself at random coordinates.

**Comment by TotallyMehis** [comment]
Done.
