### ISSUE TITLE
Additional option for ZM observer mode

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#25]
ZM 1.2.1 had this feature and although it was a bug it was very useful. The thing was simple, when you hold Tab (+showscores), you were able to rotate your camera/view without toggling "Free-Cam" mode. It'd be great to get it back in ZMR.

**Comment by TotallyMehis** [comment]
Already done: a7cd0678f0fdf5fbf2c06b06fd5188c0b0d66313
