### ISSUE TITLE
Some HL2 weapons still left in the code

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#26]
Weapon_crowbar and weapon_rpg still can be obtained with "impulse 101".

**Comment by DoofusCockslap** [comment]
Forgot to mention that weapon_annabelle and weapon_cubemap are still there too (Not sure about annabelle though).

**Comment by xXxToxicBlueDustxXx** [comment]
well the cubemap weapon is for testing cubemaps of a map so its is need for mappers
