### ISSUE TITLE
Expiring zombies not clearing edicts

### ISSUE THREAD

**Issue by L1pE** [zm-reborn/zmr-game#260]
Expiring a zombie as ZM will not clear an edict like having it die any other way does. Someone could cause an edict limit crash with this if determined enough. Appears to be because of the skull gib it creates, which should just be made client-side anyway as it already doesn't interact with anything that isn't static.

Having the skulls fade away with time and/or after a certain number are created would be good for performance reasons too.

**Comment by TotallyMehis** [comment]
Gibs are now spawned on the client, so this will no longer be a problem.
