### ISSUE TITLE
ZM popup windows

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#27]
1. There should be an option to switch between classic ZM Trap popup window and the new "dynamic" one that moves around when you're moving. I'm sure that I am not the only one who doesn't like the new one because it's very uncomfortable to play with it like that.
2. The big "cancel" button in the bottom middle of zombie spawn menu is missing. Re-add it back, please..

**Comment by TotallyMehis** [comment]
Both: 55f2222f129c274a781c64be85a146c118679558
