### ISSUE TITLE
Mouse wheel cannot be unbound from ZM height movement

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#271]
MHWHEELUP and MWHEELDOWN cause ZM view to move vertically down and up respectively. 

These appears to not be set as a regular key bind and are hard coded, meaning that if you bind the mouse wheel to anything else while ZM, you still move vertically when using that bind.

There are keybind settings in the options for moving the ZM view up and down, but they are unused by default and separate from the current mouse wheel scrolling. I recommend these keybinds be set to the mouse wheel and the hard coding removed so we have the option of using it for other things.

**Comment by TotallyMehis** [comment]
They're now bindable. Commands: +zm_cmd_moveup/+zm_cmd_movedown
