### ISSUE TITLE
World completely black when near glowing items on Steam ver

### ISSUE THREAD

**Issue by L1pE** [zm-reborn/zmr-game#272]
Running on Linux, on latest Steam ver, the world turns black when going near an item with weapon/ammo glow on, the only things visible are viewmodels, the HUD and the glow itself. This does not happen on Beta 4.

![zm_tetris_new42-epic30000](https://user-images.githubusercontent.com/11803296/63657101-dd14fd80-c78c-11e9-92de-8a25f6be0324.jpg)

Probably related to #270

**Comment by TotallyMehis** [comment]
Closing this for now.
