### ISSUE TITLE
Hulk and banshee head hitboxes don't work properly

### ISSUE THREAD

**Issue by L1pE** [zm-reborn/zmr-game#277]
The top of the banshee's head hitbox doesn't register hits, and will let shots go right through if it doesn't intersect with a different hitbox. The sides of the head hitbox appear to work fine.

Hulk's head hitboxes appear to simply not work at all no matter which side of it is hit.

Made a vid showcasing this: https://www.youtube.com/watch?v=avWcyX_5T8A

**Comment by L1pE** [comment]
After seeing this vid: https://www.youtube.com/watch?v=q0l0mRV7UC8 I remembered this issue and decided to check it out again comparing the bounding boxes.

In the case of the banshee, this does appear to be the root of the problem, as his attacking and squirming anims put his head and arms well above his bounding box (as well as allowing them to go through geometry). This also applies somewhat to Shambler's arms.

However, the hulk has his head well within his bounding box with room to spare, and his arms register hits normally while those are always outside his bounding box.

**Comment by TotallyMehis** [comment]
Hulk has increased bounds to compensate for the arms and head as seen here:

https://github.com/zm-reborn/zmr-game/blob/1a545d466cfa7ac623e66daf83dc62f0c5690b60/mp/src/game/server/zmr/npcs/zmr_hulk.cpp#L64-L68

Same can be applied for the rest of the zombies. I'll do so for the Banshee at least.

This was addressed previously in #95 but Hulk head hitbox still doesn't seem to work correctly. I'll see what I can do about it.

**Comment by TotallyMehis** [comment]
It was caused by a negative hitbox size...

https://github.com/zm-reborn/zmr-assets/commit/0906636572887b358e75078e94d010e09d8fe4cf
