### ISSUE TITLE
Bullet Fall-Off Distance

### ISSUE THREAD

**Issue by TheRenegadist** [zm-reborn/zmr-game#297]
There's a certain range at which bullets fired from weapons fade off into nothing instead of continuing their path until they hit a surface or leave the map. You'll notice this especially on the OverUnder where you'll fire from a distance and nothing will happen, bullets/buckshot should at least travel until they're stopped instead of disappearing in mid-air.

**Comment by TotallyMehis** [comment]
Handled in: 8b4c843b93e0e0d74adbf9a6943d4f676d570ad6
