### ISSUE TITLE
"Pi" player model causes crashes on Linux

### ISSUE THREAD

**Issue by L1pE** [zm-reborn/zmr-game#315]
When used by a player or bot the "Pi" player model crashes the game on Linux, by default only when viewed close enough to it, and having r_lod on anything other than -1 makes it crash from any distance. It seems necessary to have at least another human model around as well for the crashes to happen.

Dump file attached.
[crash_20200430005358_1.dmp.tar.gz](https://github.com/zm-reborn/zmr-game/files/4579208/crash_20200430005358_1.dmp.tar.gz)

**Comment by TotallyMehis** [comment]
https://github.com/zm-reborn/zmr-files/commit/66c6a5486e66d17e91858a33ad458e14902a7419

Should fix the issue.

**Comment by L1pE** [comment]
Bit of a late reply, but I can confirm the new Pi model doesn't cause crashes anymore, thanks. And for reasons I can't explain, now neither does the G-man model in the "remix" ver of blackmesa, or the rebel body room in red_horror, which both used to, even in my mod install which should have no new files. Iunno.
