### ISSUE TITLE
Missing "func_detail_blocker" entity

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#327]
It does exist in the FGD (at least in Source SDK 2013 Base MP's Hammer), but when running the map that was compiled with the 
said entity in ZMR, the console only spits out "Attempted to create unknown entity type func_detail_blocker!"

**Comment by TotallyMehis** [comment]
That's because you're not using the ZMR compiling tools, which you can find here: https://steamcommunity.com/groups/zmreborn/discussions/0/2579854400735942989/ .

**Comment by DoofusCockslap** [comment]
Alright, thanks for a reminder.
