### ISSUE TITLE
Aux Power HUD still exists and when you go underwater, it shows up.

### ISSUE THREAD

**Issue by xDadiKx** [zm-reborn/zmr-game#34]
Aux Power hud still exists and shows up when you go underwater.
![zm_ammodrop0001](https://user-images.githubusercontent.com/13087761/29862864-b540b366-8d65-11e7-8006-c92fc719ea03.png)

**Comment by TotallyMehis** [comment]
Already fixed: https://github.com/zm-reborn/zmr-game/commit/75b616c2459406078330f9acb8a5be016d8872fd
