### ISSUE TITLE
Crash when impacted by explosive barrels thrown by zombies

### ISSUE THREAD

**Issue by caballs** [zm-reborn/zmr-game#38]
Zombies can cause crashes by slapping explosive barrels torwards players. The crash occurs when the barrel impacts the player; the explosion does not register, or is the direct result of the server timing out.

![crash](https://user-images.githubusercontent.com/31574778/29998934-1fc37f06-9005-11e7-889b-9121ecccdf9e.jpg)

**Comment by TotallyMehis** [comment]
Not it https://youtu.be/aYbbE6FodDE

**Comment by caballs** [comment]
Well, shit. It had happened once before on zm_docksofthedead with the regular explosive barrels, too. Maybe it was just luck of the draw?

**Comment by TotallyMehis** [comment]
Most likely caused by 0b12531924d916042673f94704ab6e1f9d2aed62.
