### ISSUE TITLE
Zombie fade-in on spawn is missing.

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#42]
Zombies in 1.2.1 fade in when spawned (A feature added in 1.2.0). This is missing from Reborn. Possibly a deliberate choice? Which would make sense for hidden spawns, but I personally think spawns from regular spawn points look better with the fade in.

**Comment by TotallyMehis** [comment]
cb02e07c85de1c50ccedc6dc2774c86345fe49ca
