### ISSUE TITLE
Team switching with plugins is broken

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#44]
Any attempt to force a clients team to change from spectator to human using ChangeClientTeam in sourcemod causes the player to join the human team but retain spectator functionality. They also drop to the floor where they are currently spectating.

The falling down where you are may be related to the fact that spectators are no longer moved to the spawn when the round starts, like in 1.2.1.

**Comment by TotallyMehis** [comment]
Fixed: 39ac2bc5ad9e239afd14dbf40092ae097bea8d93
