### ISSUE TITLE
Fall damage is heavily reduced from the original values.

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#48]
As such a fall from a height which would kill a human in 1.2.1 will allow you to survive in Reborn.

To reproduce: 
Open docksofthedead, noclip up and stand on the concrete walls either side of the generator that powers the lights. 
Falling from this height onto the ground will deal ~18 damage in 1.2.1, but only deal ~4 damage in Reborn.

**Comment by TotallyMehis** [comment]
034708c44121725df04c1889be3eb5299456769e
