### ISSUE TITLE
Feature Request: Allow chat colours

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#50]
No colour manipulation of that chat is allowed (like in 1.2.1), all text appears yellow. The ability to modify the colours produced by plugin text would be nice.

**Comment by TotallyMehis** [comment]
Not true. Source 2013 supports more chat colors. You can define custom ones with \x07FFFFFF or \x08FFFFFF00 for alpha.

**Comment by DevilMudger** [comment]
The **engine** may support colours, but for whatever reason I cannot get chat messages from advertisements.smx to display colour in Reborn. Either I'm defining the config wrong, which I've gone over several times now (I've tried using colour codes directly, or colour names), or the lack of colour in messages from ZM 1.2.1 has carried over. 

I'm sure that the 2006 engine supported certain colours too, but old ZM would always refuse to display them. Only showing text in grey.

Entirely possible I'm fucking something up here.
