### ISSUE TITLE
Explosive barrel doesn't disappear after triggered to break / explode.

### ISSUE THREAD

**Issue by xDadiKx** [zm-reborn/zmr-game#53]
I was making a trap and I used a info_manipulation entity to make it.
I set the output to be...
On Click of Set of Trap Button
V
barrelexplosive
V
Break
It causes it to explode, but the barrel stays, just not solid and interactable.

**Comment by DoofusCockslap** [comment]
Same issue applies to pretty much any breakable prop. It also happens if you use ent_fire on the breakable props too. There is a simple way to fix it on your map without changing the game code is an extra Output "Kill" with 0.01 delay for breakable props.

**Comment by TotallyMehis** [comment]
a13f0809cf7cee9b8be5423d17db021da2dad0af
