### ISSUE TITLE
Certain custom textures don't display properly

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#54]
zm_alcazar works fine in 1.2.1, but in reborn almost all the custom textures display as purple checker boards. The paintings show up fine, but seemingly nothing else.

I've looked about to see if I can find another map with the same issue. The only evidence I've found of it elsewhere so far is a couple of missing texture spots on the shed in the corner of zm_echo_mainstreet_b2 which do not appear when loading the map in 1.2.1.

Hoping this can be fixed modside.

**Comment by TotallyMehis** [comment]
zm_alcazar_b8 packed the textures wrong. All missing textures have "materials//" at the start.

Valve has made string formatting stricter, hence why it worked in 2006. There's probably nothing we can do and even if there was I wouldn't want to enable bad practice.
