### ISSUE TITLE
Player damage from physics is dramatically lower than expected

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#64]
The damage that players take from impact with props is way lower than it was in ZM 1.2.1

Might be related to shamblers not being able to damage props?

Evidence:
https://www.dropbox.com/s/2lhgoj5b0hbjz1q/zm_hard_Impact.bsp?dl=0

In the above map, the buttons left to right when not moving from the spawn deal 10, 20 and 50 damage to the player respectively.
In ZM 1.2.1, all three buttons are an instant kill.

https://www.dropbox.com/s/z8bbryhzgz1mxb4/zm_hard_Impact_slow.bsp?dl=0

In the above map, the same set up deals 10 damage in ZM:R from both the middle and right buttons (left doesn't hit the player). In ZM 1.2.1, the middle button deals 70, and the right button is an instant kill.

Unclear if this is a result of the trap physics being interpreted differently in the new engine causing the props to be slower, or if the player is genuinely taking less damage from the same force. I think it is the latter, as shamber thrown damage appears lower too.

The result is that it is almost impossible to kill players with props thrown by shamblers, and certain physics related traps now deal significantly less damage than intended.

(Thanks to Psycho for the maps)

**Comment by TotallyMehis** [comment]
ea1bae2c777082f596966fd09b4d034e9da439c8
