### ISSUE TITLE
Hidden Summoned zombies not facing the direction of ZM

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#66]
In 1.2.1 every Hidden Summoned zombie was facing the exact same direction/angles the ZM's camera was facing. Let's say ZM is looking at North, hidden zombie that was spawned by ZM will be facing North as well. This was very useful for tactical ambushing without messing up the hidden zombie position. In ZMR hidden zombies spawn always under default angles (0 0 0, as it seems).

**Comment by TotallyMehis** [comment]
07b9d0bc78ae3f76432044c28ebc2789a46e1ed4
