### ISSUE TITLE
Default zombie resource costs and population costs are different

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#70]
Some of these I gather are intentional, but some of them are not?

I've listed the differences here in case any of these are not intended.

Banshee
ZM 1.2.1  Res: 60     Pop: 4
ZM: R       Res: 50     Pop: 3

Hulk
ZM 1.2.1  Res: 60     Pop: 3
ZM: R       Res: 75     Pop: 5

Drifter
ZM 1.2.1  Res: 25     Pop: 2
ZM: R       Res: 40     Pop: 2

Immolator
ZM 1.2.1  Res: 100     Pop: 5
ZM: R       Res: 100     Pop: 8

**Comment by TotallyMehis** [comment]
Current values on dev branch:

**Refill rate (per 5 seconds):**
Min: 35 (1 human)
Max: 100 (16 humans)

**Pop cost:**
Shambler: 1
Banshee: 6
Hulk: 5
Drifter: 2
Immolator: 8

**Cost:**
Shambler: 10
Banshee: 45
Hulk: 70
Drifter: 35
Immolator: 100


I'm not planning on adding a banshee limit as it makes banshees completely useless against 1/2 players, and is the core reason why banshee usage is punished through pop cost.

**Comment by DevilMudger** [comment]
I'm not sure I agree with the modified min/max rate or banshees being quite so cheap but everything else I agree with.
