### ISSUE TITLE
ZM resource fill rates are based only on the human team

### ISSUE THREAD

**Issue by DevilMudger** [zm-reborn/zmr-game#71]
In ZM 1.2.1, the resource rate of the ZM was based on the number of players alive and dead, in Reborn the rate is based only on humans and so drops off as the round continues.

I'd would argue the old behaviour is better, as the further into a level the survivors get, the harder it becomes for the ZM to stop them, and the further into the level the survivors get, the more humans the ZM will have killed. Diminishing the resources to a crawl at the end can make a ZMs job very hard.

I recognise the virtues of the new behaviour, so a happy middle ground would be to add a cvar to toggle between old behaviour and new, preferably defaulting to old.

**Comment by TotallyMehis** [comment]
ec0739b614d6900d6a995baaa464a36dfe84d1f8

**Comment by DevilMudger** [comment]
If this new Cvar is based on the count at the start of the round, rather than an ongoing player count, wouldn't it fail to produce an accurate rate, if it is the first round and the round starts with 2 people, and then another 13 are added by joingrace (or latespawn)?

**Comment by TotallyMehis** [comment]
No, it accounts for it.
