### ISSUE TITLE
Suggestion: Remove The Default HL2DM Footsteps behaviour to HL2's Style ( No Override The Function )

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [zm-reborn/zmr-game#8]
As it says in the title, to achieve that you must look in the following files:

- remove in c_hl2mp_player.h
`void	PrecacheFootStepSounds( void );`

- remove in hl2mp_player.h
`void	PrecacheFootStepSounds( void );
virtual void PlayStepSound( Vector &vecOrigin, surfacedata_t *psurface, float fvol, bool force );`

- remove in hl2mp_player.cpp
`PrecacheFootStepSounds();`

- remove this functions hl2mp_player_shared.h
`void CHL2MP_Player::PrecacheFootStepSounds( void )
void CHL2MP_Player::PlayStepSound( Vector &vecOrigin, surfacedata_t *psurface, float fvol, bool force )`

**Comment by TotallyMehis** [comment]
What exactly is the difference between the HL2 and HL2DM footsteps?

**Comment by xXxToxicBlueDustxXx** [comment]
when you play HL2DM you heard the citizen's foot steps and not the terrain based footsteps

**Comment by TotallyMehis** [comment]
Yea, that makes sense. I just made a commit to fix that.
