### ISSUE TITLE
FOV customization option (ZM only feature)

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#80]
Sometimes the default FOV of 90 is not enough when it comes to gameplay as ZM.

**Comment by DevilMudger** [comment]
The ability to modify the FOV in game for any team, not just ZM, is something other players have wanted in ZM for a while.

**Comment by TotallyMehis** [comment]
Use the zm.cfg and survivor.cfg to set FOV per team. (zm_cl_fov)
