### ISSUE TITLE
Character Skins

### ISSUE THREAD

**Issue by ConAndreas** [zm-reborn/zmr-game#9]
Our character's skin changes to a random one whenever the options tab is opened or when another one is selected.

**Comment by TotallyMehis** [comment]
This is a workaround for a problem caused by the Steampipe update. Setting player models doesn't work. Same problem exists in HL2DM. I will eventually re-do the model panel.

**Comment by xXxToxicBlueDustxXx** [comment]
you can use the system that was used in FIREFIGHT RELOADED
https://github.com/FIREFIGHT-RELOADED/FIREFIGHT-RELOADED-src-sdk-2013/blob/master/sp/src/game/client/gameui/PlayerModelDialog.cpp

**Comment by TotallyMehis** [comment]
We have our own player model panel now: 06a18bb4202a975e1d0ab324b5e0c3e7ba4dd18b
