### ISSUE TITLE
Bug: Playermodel Head Shaking

### ISSUE THREAD

**Issue by TheRenegadist** [zm-reborn/zmr-game#91]
Seems the heads on the playermodels shake for no reason.

**Comment by TotallyMehis** [comment]
Yeah, that has always happened.
I updated the look-at method, hopefully it works. 02f9121f8b0d1462abdae0801de1aeca4e7505d7

**Comment by TheRenegadist** [comment]
Yep, the heads stopped shaking or so it seems but now the eyes go all over the place. Also made an issue to address this.

**Comment by TheRenegadist** [comment]
So I guess we can close this one since it is technically fixed and focus on the eyes now.
