### ISSUE TITLE
Bug: Jittery Movement

### ISSUE THREAD

**Issue by TheRenegadist** [zm-reborn/zmr-game#92]
Started noticing jittery movement when playing as the survivor, most notable when landing from a crouch jump or general movement. Almost acts like rubber-banding but on a smaller scale.

**Comment by xXxToxicBlueDustxXx** [comment]
HL2DM uses base_playeranimstate these anim system dont come whit MP if you check multiplayer_animstate is fully smooth animations tofix this is reimplement the MP anim state that make tony sergi to source 2007
