### ISSUE TITLE
More players models and new points system for the survivors.

### ISSUE THREAD

**Issue by commandos966** [zm-reborn/zmr-game#97]
For sure, i'm not saying too much but how about to add donation system? i would like to support your project because i'm zombie master fan so yeah. First new players models, like custom ones (like combine soldier and css player models or anything you like).Second Points system for survivors like for each kill for the normal zombie(foot zombie) 1 point and for banshee 3 points , etc and add new skill menu for the survivors, like sprint , more ammo , more health , auto-regeneration for ammo and health and melee damage.i'm not asking so much but i just want to help you with this idea so yeah i hope to see zombie master again with more players. Well, i'm new to Github so i don't know how to add Labels so i prefer to call it enhancement.EDIT:I forgot to say something about the points system, how about to add custom servers (with points system) and normal servers?(the normal ZM).

**Comment by TheRenegadist** [comment]
Seems this can all be accomplished via server plugins/server addons, not something that should be in the default base game in my opinion.
