### ISSUE TITLE
Update the Old animation system to use the TF2's system ( old Source 2007 HLDM animation system )

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [zm-reborn/zmr-game#98]
originally the animation system was fully MP Friendly (smooth transition without Jittery ) but in the newer engine the changes that made Tony Sergy has gone include the old Orange Box Scoreboard and misc fixes including the MP Animation system, originally in the Source2006 the animation system uses layers to override a existent anim ( that was working the HL2 Leak and goldsource )  but not was fully MP Friendly ( in someone PC can make high ping error ( so the anims can see Jittery ) so, if you have a Source2007 and if you are in thirdperson mode you can see that the anims are smooth so, will be god to ZM:R Add these anims

For More Info you can check this Commit https://github.com/goldeneye-source/ges-code/commit/64a4a8d9b7d95baf085e566b678b9007c7b77580

**Comment by TotallyMehis** [comment]
Are there any real advantages other than fixed thirdperson anims?

**Comment by xXxToxicBlueDustxXx** [comment]
nope, the only way is fixing the animation states is replacing the animation layers (base_playeranimstate.cpp) whit one that can be MP and Coder friendly (seriously Layers can make you very angry sometimes) but the multiplayer_animstate allow to you crea very complex anims that the Goldsourcera Anim Layers

**Comment by TotallyMehis** [comment]
651b77dbc79b7d13a52793f9f6371ce1ac2e0b2d
